### ISSUE TITLE
Black Italic source file still named Celebes

### ISSUE THREAD

**Issue by kenmcd** [Lafontype/Gantari#1]
One source file name did not get changed.
Filename is: Celebes-BlackItalic.vfb

The name is Gantari inside the file.

**Comment by Lafontype** [comment]
The name has been changed to Gantari-BlackItalic.vfb

Thank you

**Comment by kenmcd** [comment]
Opps.
Source file name is now: Gantari-BlackItalic.ttf

**Comment by Lafontype** [comment]
my bad, I've fixed that.

thank you
